version: 2.1

jobs:
  pull:
    working_directory: ~/project
    docker: # run the steps with Docker
      - image: circleci/node:12.18.2-stretch  
        environment:
          GIT_AUTHOR_NAME: Welement Bot
          GIT_COMMITTER_NAME: Welement Bot
          GIT_AUTHOR_EMAIL: bot@welement.com
          GIT_COMMITTER_EMAIL: bot@welement.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cd:52:15:c6:52:bf:5a:c0:2d:cd:c0:30:9e:cb:4f:f4"
      - run: git pull origin $CIRCLE_BRANCH
      - run: |
          git commit --allow-empty -m "Pull was run! [ci skip]"
          git push origin $CIRCLE_BRANCH

workflows:
  welcome:
    jobs:
      - pull
