version: 2.1

jobs:
  pull:
    working_directory: ~/project
    docker: # run the steps with Docker
      - image: circleci/node:12.18.2-stretch  
        environment:
          GIT_AUTHOR_NAME: Welement Bot
          GIT_COMMITTER_NAME: Welement Bot
          GIT_AUTHOR_EMAIL: bot@welement.com
          GIT_COMMITTER_EMAIL: bot@welement.com
    steps:
      - checkout
      - run: git pull origin $CIRCLE_BRANCH
      - run: |
          git commit --allow-empty -m "Pull was run!"
          git push origin $CIRCLE_BRANCH

workflows:
  welcome:
    jobs:
      - pull
