name: GitHub Actions Demo
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "head_ref is ${{ github.head_ref }}"
      - run: echo "base_ref is ${{ github.base_ref }}"
      - run: echo "ref is ${{ github.ref }}"
      - run: |
          echo "Setting job conditional output variables"
          echo ""::set-output name=SELECTED_COLOR::green"


  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo "Value is ${{ needs.init.outputs.SELECTED_COLOR }}"
      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v2
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "🍏 This job's status is ${{ job.status }}."

# THINGS I NEED TO FIGURE OUT

# 1. caching and restoring yarn node_modules
# 2. 