name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      is_main: ${{ steps.is_main.outputs.value }}
    steps:
      - name: main Check 
        id: is_main
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]
          then
            echo '::set-output name=value::true'
          else
            echo '::set-output name=value::false'
          fi
      - run: echo 'color set ${{ steps.is_main.outputs.value }}'


  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo ${{ needs.init.outputs.is_main }}

# THINGS I NEED TO FIGURE OUT

# 1. caching and restoring yarn node_modules
# 2. 