name: GitHub Actions Demo
on: [pull_request]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "head_ref is ${{ github.head_ref }}"
      - run: echo "base_ref is ${{ github.base_ref }}"
      - run: echo "ref is ${{ github.ref }}"
      - run: |
          echo "Setting job conditional output variables"
          echo ""::set-output name=SELECTED_COLOR::green"


  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo "Value is ${{ needs.init.outputs.SELECTED_COLOR }}"

# THINGS I NEED TO FIGURE OUT

# 1. caching and restoring yarn node_modules
# 2. 