name: GitHub Actions Demo
on: [pull_request]
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      SELECTED_COLOR: ${{ steps.set_vars.outputs.SELECTED_COLOR }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "head_ref is ${{ github.head_ref }}"
      - run: echo "base_ref is ${{ github.base_ref }}"
      - run: echo "ref is ${{ github.ref }}"
      - name: Setting variables 
        id: set_vars
        run: |
          echo "Setting job conditional output variables"
          echo '::set-output name=SELECTED_COLOR::green'
      - run: echo 'color set ${{ steps.set_vars.outputs.SELECTED_COLOR }}'


  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo ${{ needs.init.outputs.SELECTED_COLOR }}

# THINGS I NEED TO FIGURE OUT

# 1. caching and restoring yarn node_modules
# 2. 