name: GitHub Actions Demo
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      is_master: ${{ steps.is_master.outputs.value }}
    steps:
      - name: Master Check 
        id: is_master
        run: |
          if [ ${{ github.ref }} = 'refs/heads/master' ]
          then
            echo '::set-output name=value::true'
          else
            echo '::set-output name=value::false'
          fi
      - run: echo 'color set ${{ steps.is_master.outputs.value }}'


  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo ${{ needs.init.outputs.is_master }}

# THINGS I NEED TO FIGURE OUT

# 1. caching and restoring yarn node_modules
# 2. 